wps-cloudformation-template.yaml

Creates the resources but doesn't work end to end yet.
Surprisingly API gateway turned out to be more complicated than the other stuff, so I skipped it.
s3LambdaCodeBucket needs to be in the same region as the stack. So to bring up a stack in a new region you need to create an s3 bucket in the new region and put the lambda zip file in it.

A first draft of a cloud formation template to bring up the wps stack

---

javaduck-image/bin/aggregate.sh

I keep having to look into the javaduck-image directory to see whats there - time to remove it as its no longer used.

Remove aggregate.sh - no longer used

---

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
wps-cloudformation-template.yaml

Copying in 1K chunks takes a very long time for large datasets.

Fixes #95 - up the amount of data copied at a time from 1KIB to 10MB.

---

wps-cloudformation-template.yaml

dev.properties 
```
requestHandlerCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/request-handler-0.01-lambda-package.zip
jobStatusCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/job-status-service-0.01-lambda-package.zip
dockerImage=615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/javaduck:sandbox
geoserver=http://geoserver-123.aodn.org.au/geoserver/imos/ows
hostedZoneName=dev.aodn.org.au
wpsDomainName=**_YourCustomDomainName_**
acmCertificate=arn:aws:acm:us-east-1:615645230945:certificate/06e50848-29a7-47c3-8a3f-c3212b608a8d
```
Fix for https://github.com/aodn/aws-wps/issues/92

Fixed the custom domain name creation dependency

---

wps-cloudformation-template.yaml

Set default max heap size to 512m.
Without specifying a value for max heap size, java uses 1/4 of the memory available on the instance it is running on as the default which results in the allowed memory for the job being exceeded on larger aggregations.
I was running on an r4.large instance which has 15.25GB memory, which meant java would have been using a max heap size of around 3.8Gb, but the job is limited to 2GB.

Fixes #120

---

.travis.yml
aggregation-worker/pom.xml
job-status-service/pom.xml

Use s3 maven repository to source current version of dependent IMOS wars.
Copy dependencies in package phase so it doesn't prevent compilation/unit testing on clean build
Ensure it compiles and unit tests pass with travis.

Fixes #125

---

aggregation-worker/pom.xml

Fixes issue finding NetcdfReader when running aggregation worker.

Use unique timestamp when adding snapshot dependencies as per manifest

---

integration-testing/pom.xml
integration-testing/src/test/java/au/org/emii/wps/it/DescribeProcessIT.java
integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
integration-testing/src/test/java/au/org/emii/wps/it/GetCapabilitiesIT.java
integration-testing/src/test/java/au/org/emii/wps/util/GPathMatcher.java
integration-testing/src/test/java/au/org/emii/wps/util/NcmlValidatable.java

to ensure config is being applied as required
Note provenance and timeseries checks are currently failing due to #144 and #143
Requires #141 for other aggregation tests to work.

Add some content checks for aggregations and provenance documents

---

wps-cloudformation-template.yaml

Also, previous maxHeapSize setting was not actually being used - was being passed as an argument to the aggregator not to the jvm.  Use JAVA_TOOL_OPTIONS environment variable to set the max heap size instead.

Allow custom ami to be specified for compute environment

---

wps-cloudformation-template.yaml

Need to change the version (name) whenever an unmodifiable setting
(instance type, ami, max spot price etc)  is changed to force
the compute environment to be replaced otherwise the stack update fails
because it can't update the existing compute environment.
Looked at including the template version number, but that would trigger the
compute environment to be replaced every deployment which would create
unnecessary dependencies on running jobs.

Use a version number in compute environment name to trigger replacement

---

job-status-service/pom.xml
request-handler/pom.xml
wps-cloudformation-template.yaml

These are changes which need to be made if we go with using the "aws cloudformation package" command for lambda code deployment. 
Note how the lambda code is referenced:   ```Code: ./job-status-service/target/job-status-service-lambda-package.zip```
The package command takes the zip file at this relative path, uploads it to s3, and then creates a new temporary template file which points to the code on s3: 
```      
Code:
S3Bucket: imos-binary-dev
S3Key: lambda/df9d13f87d429ee7ab4b6c88527003ad
```
This makes it easy to deploy our local code changes. Some disadvantages I can think of are:
* it forces us to keep the lambda code in the same place as the template (but this is what we're already doing)
* unlike the current setup we won't be able to set a parameter to point to an already …

Lambda code package proposal

---

dev.properties
job-status-service/src/main/java/au/org/aodn/aws/wps/lambda/JobStatusServiceRequestHandler.java
job-status-service/src/main/resources/templates/job_queue_html_template.ftl
job-status-service/src/main/resources/templates/job_status_html_transform.xsl
wps-cloudformation-template.yaml
wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java

Alternative solution to https://github.com/aodn/aws-wps/pull/180. I think this is better because I'd expect a particular template to be tightly coupled to a particular logo. To change the logo a dev would just have to change the template to point to a different location.

Place logo url directly in templates rather than promulgating through stack

---

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java
wps-common/src/main/java/au/org/aodn/aws/util/EmailService.java
wps-common/src/main/java/au/org/aodn/aws/util/EmailTemplateManager.java

Resolve https://github.com/aodn/aodn-portal/issues/2585 by changing email to contain a link to the the status page for the job rather than the raw output file link.

Fix completed email link

---

aggregation-worker/src/main/java/au/org/emii/aggregator/au/org/emii/aggregator/config/AggregationOverridesReader.java

Resolves Issue #221
Verify by running up a stack with a nonsensical URL set for the location of the template.xml file (AGGREGATOR_TEMPLATE_FILE_URL environment variable - templatesURL cloudformation stack parameter) or point to a broken file (some JAXB issue).  All aggregations should fail + report a WPS error.

Throw exception when unable to find or load aggregation overrides config.

---

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java
wps-common/src/main/java/au/org/aodn/aws/util/EmailService.java

Add administrator email address as BCC to error emails when they occur - rather than sending a separate email to administrator email.

Change email service to allow BCC recipient for error emails.  

---

wps-cloudformation-template.yaml

Advantages of this are:
1. when we add a new stack we only have to add the new bucket to one place (the deployment job)
1. when doing development work on aws-wps we can easily set our own persistent bucket rather than being forced to use an ephemeral bucket.
@jonescc @ccmoloney

Set bucketName parameter to be given any bucket name.

---

request-handler/pom.xml
request-handler/src/main/java/au/org/aodn/aws/wps/operation/ExecuteOperation.java
request-handler/src/main/java/au/org/aodn/aws/wps/operation/JobMapper.java
request-handler/src/main/java/au/org/aodn/aws/wps/operation/JobSettings.java
wps-cloudformation-template.yaml
wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java

To allow online resource monitor to regularly perform test transactions without affecting production users.  Test transaction triggered by adding a TestMode input to the execute request with a LiteralData value of 'true'.
Compute environment should be identical to the production environment so as to be a meaningful test.

Add support for a test transaction queue + compute environment

---

cloudformation.sh

Make parameters 'named' and add support to pass stack tags (multiple if required) to the aws cloudformation deploy command.

Named parameters and stack tags

---

wps-cloudformation-template.yaml

Node 4.3 is no longer available in Lambda

Update nodejs version

---

requests/request.xml

The example request was looking for gs:gogoduck but we deploy it as gs:GoGoDuck

changed gogoduck to GoGoDuck

---

integration-testing/src/test/java/au/org/emii/wps/it/DescribeProcessIT.java

Needs to match the new http status (400) as implemented in https://github.com/aodn/aws-wps/pull/277/

Fix test for DescribeProcess when given unknown process

---

Jenkinsfile

Note: don't merge until associated Jenkins config management PR is merged.
This allows the `docker push` command to find the `docker-credential-ecr-login` binary in the Jenkins $HOME/bin directory.

Jenkinsfile: set PATH to find docker ECR credentials helper script

---

wps-cloudformation-template.yaml

For https://github.com/aodn/backlog/issues/2558
The new AMIs can be seen in the AMI section of the AWS console in production-admin account

Use newly build AMIs with gp3 storage attached

---

aggregation-worker/pom.xml
pom.xml

I did have a brief look at what it would take to get https://content.aodn.org.au working instead, but it would require us to set up a new cloudfront distribution and point at it instead of the bucket, which I think would be overkill for fixing a small issue like this (especially when we do already have an https endpoint, even if the url is a bit messy)
Fixes https://github.com/aodn/issues/issues/1025
Successful build in Github Actions can be [seen here](https://github.com/aodn/aws-wps/actions/runs/969952704)

Point to https version of our content repository

---

wps-cloudformation-template.yaml

r5 has improved specs over r4/r3, with no documented down-sides, so any application that works with r3/r4 should work with r5. Therefore we should have it as an option. 
(r5 didn't exist yet last time we edited the instance types)

Add r5.large to potential instance type

---

wps-cloudformation-template.yaml

- "Name" so they're easier to spot in the EC2 instances console
- "AutoOff" so they don't get deleted at 7pm each day (if the parent stack itself have AutoOff=false then they'll still get deleted with it)
For https://github.com/aodn/backlog/issues/3268

Add some useful tags to wps spot instances

---

aggregation-worker/Dockerfile

Example job using the new docker image: https://xvrxr7mrkc.execute-api.ap-southeast-2.amazonaws.com/LATEST/wps/jobStatus?format=ADMIN&jobId=f836f1b1-7202-4319-8e32-1b9b89a6ee89
For https://github.com/aodn/backlog/issues/3708

Upgrade aggregation workers docker to ubuntu 20

---

wps-cloudformation-template.yaml

Noticed while checking aws-wps costs for architecture review that tags were only working for test instances, and yep TestComputeEnvironment hsa the "Tags" key a level lower in the yaml.

Move non-test ec2 instance tag to correct location
