aodn/aws-wps

aggregation-worker/Dockerfile, aggregation-worker/pom.xml, aggregation-worker/scripts/deploy.sh, pom.xml, request-handler/pom.xml
To test
`mvn clean package install`
=> Changed deploy method and made aggregation-worker module of aws-wps

aggregation-worker/pom.xml, aggregation-worker/scripts/docker-build.sh, aggregation-worker/scripts/docker-deploy.sh
Enabled following command 
`aws-wps> mvn clean package deploy`
=> Enabled mvn deploy form the parent project

README.md, request-handler/src/test/java/au/org/aodn/aws/wps/WpsRequestHandlerTest.java
Updated ReadMe.md + WpsRequestHandlerTest
=> Updated WpsRequestHandlerTest with latest request + config.

wps-cloudformation-template.yaml
Currently falls over when the job starts running, the only message in the log is "Error: Unable to access jarfile /opt/aggregator/aggregation-worker-1.0-SNAPSHOT.jar But that's much further than before these changes.
=> Some fixes to get the cloud formation stack working further in practice

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/ExecuteOperation.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/EnumOperation.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/ExecuteStatusBuilder.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/S3StatusUpdater.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/StatusHelper.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
Fixing up the WPS outputs - including output links in the status document when successful.
=> Improve wps outputs

aggregation-worker/pom.xml, aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/util/EmailService.java, aggregation-worker/src/main/java/au/org/emii/util/EmailTemplateManager.java, aggregation-worker/src/main/resources/application.properties, aggregation-worker/src/main/resources/templates/jobComplete.vm, aggregation-worker/src/main/resources/templates/jobCompleteSubject.vm, aggregation-worker/src/main/resources/templates/jobFailed.vm, aggregation-worker/src/main/resources/templates/jobFailedSubject.vm, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
Add following to application.properties for local testing
```
AWS_REGION=us-east-1
OUTPUT_S3_FILENAME=output.nc
STATUS_S3_BUCKET=wps-lambda-status
STATUS_S3_FILENAME=status.xml
OUTPUT_S3_BUCKET=wps-lambda-status
```
Run using following command 
`docker run -e "AWS_REGION=us-east-1" -e "AWS_ACCESS_KEY_ID=yourkeyid" -e "AWS_SECRET_ACCESS_KEY=yourkey" -i -t javaduck:latest "imos:acorn_hourly_avg_rot_qc_timeseries_url" "TIME,2017-01-01T00:00:00.000Z,2017-01-07T23:04:00.000Z;LATITUDE,-33.18,-31.45;LONGITUDE,114.82,115.39" "application/x-netcdf" "ankit.bhasin@utas.edu.au"`
=> Added email service to update user

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, wps-cloudformation-template.yaml
=> Worker now supports email parameter

wps-cloudformation-template.yaml
Addressed review comments for https://github.com/aodn/aws-wps/pull/33
Old PR https://github.com/aodn/aws-wps/pull/38
`aws --region eu-central-1 cloudformation deploy --template-file wps-cloudformation-template.yaml --stack-name ankit2 --parameter-overrides s3LambdaCodeFilename=request-handler-0.01-lambda-package.zip s3LambdaCodeURL=https://imos-binary.s3-ap-southeast-2.amazonaws.com/jobs/aws_wps_systest/6/request-handler-0.01-lambda-package.zip dockerImage=104044260116.dkr.ecr.us-east-1.amazonaws.com/javaduck:latest geoserver=fsda securityGroup=sg-7746a71e subnets=subnet-9e0003e6 --capabilities CAPABILITY_IAM`
=> Adding config files to s3

wps-cloudformation-template.yaml
Related PR https://github.com/aodn/aws-wps/pull/44
=> Added geoserver env to worker

aggregation-worker/pom.xml, aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/aggregator/converter/Converter.java, aggregation-worker/src/main/java/au/org/emii/aggregator/converter/NetCDFConverter.java, aggregation-worker/src/main/java/au/org/emii/aggregator/converter/TextCsvConverter.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
Added converters to cater for netcdf & csv output.
Associated change:  https://github.com/aodn/netcdf-iterator/pull/5/files
=> Csv conversion

deploy.sh, dev.properties, wps-cloudformation-template.yaml
To run:
1. Make sure aws cli is installed and correctly configured
1. Rename dev.properties, replacing "dev" with whatever you want your stack name to be.
1. Run the command " ./deploy.sh dev" replacing "dev" with your own stack name
=> Add script for deploying to cloudformation

job-status-service/src/main/java/au/org/aodn/aws/wps/JobStatusFormatEnum.java, job-status-service/src/main/java/au/org/aodn/aws/wps/lambda/JobStatusServiceRequestHandler.java, wps-common/src/main/java/au/org/aodn/aws/util/JobFileUtil.java
Set content-type appropriately on response
Use standard mimetype strings for requested format
Fix compile error
@bhasin85  would be good to have cloudformation changes to test
=> Set content type and other changes

request-handler/src/main/java/au/org/aodn/aws/wps/exception/OGCException.java, request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/DescribeProcessOperation.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/Operation.java, wps-common/src/main/java/au/org/aodn/aws/util/JobFileUtil.java
Also addresses issue where exceptions were being returned but status code was 200.
=> Fixes #80 - more useful message for unknown process

integration-testing/pom.xml, integration-testing/src/test/java/au/org/emii/wps/it/DescribeProcessIT.java, integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java, integration-testing/src/test/java/au/org/emii/wps/it/GetCapabilitiesIT.java, integration-testing/src/test/java/au/org/emii/wps/util/Classpath.java, integration-testing/src/test/java/au/org/emii/wps/util/ClasspathResourceResolver.java, integration-testing/src/test/java/au/org/emii/wps/util/ExecuteRequestBuilder.java, integration-testing/src/test/java/au/org/emii/wps/util/Matchers.java, wps-common/pom.xml
Specify the APS WPS Stack to test by setting the WPS_ENDPOINT environment variable.
Then run mvn verify in the integration-testing directory
=> Add some integration tests for AWS WPS

wps-cloudformation-template.yaml
More than halves the time it takes to handle requests cold and warm.
=> Fixes #73 - allocate more memory for java function

job-status-service/src/main/java/au/org/aodn/aws/wps/lambda/JobStatusServiceRequestHandler.java, wps-cloudformation-template.yaml, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java, wps-common/src/main/resources/job_status_html_transform.xsl
=> Fix for #97 and #77

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, job-status-service/src/main/java/au/org/aodn/aws/wps/lambda/JobStatusServiceRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/DescribeProcessOperation.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/ExecuteOperation.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/Operation.java, wps-cloudformation-template.yaml, wps-common/src/main/java/au/org/aodn/aws/exception/OGCException.java, wps-common/src/main/java/au/org/aodn/aws/util/DescribeProcessHelper.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/ExecuteStatusBuilder.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
Fix for https://github.com/aodn/aws-wps/issues/102
=> Executeresponse fix

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/ExecuteStatusBuilder.java
Must include title of output in response
Requires https://github.com/aodn/aws-wps/pull/130
=> Fix response validation error and turn on testing for valida responses

wps-cloudformation-template.yaml
Cloudformation deploy will reload the lambda code when the version parameter is changed.
dev stack is up in development account for testing. I am happy to show you the reload from my machine.
=> Reload lambda code on version change

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
=> Fixes #142 Return provenance document as content type application/xml

wps-common/src/main/resources/templates/jobRegistered.vm
=> Consistent friendliness

aggregation-worker/src/main/java/au/org/emii/geoserver/client/HttpIndexReader.java, integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
Retrieve urls in ascending order
=> Fixes #143

wps-cloudformation-template.yaml
https://github.com/aodn/aws-wps/pull/140
https://github.com/aodn/ci-config/pull/109
https://github.com/aodn/chef/pull/618
=> CF changes for WPS Deploy Jenkins Job

wps-cloudformation-template.yaml
Also moved some related non-instance specific settings out of input parameters.
=> #164 - Only run one job at a time on an instance

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/DescribeProcessOperation.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/ExecuteOperation.java
Put a few key log lines in various places to be used for Sumo logging at some later stage.
=> Add better logging lines for Sumo log reporting/metrics.

wps-cloudformation-template.yaml
Decreases aggregation time for SRS collections by more than 25%
=> Increase aggregator chunk size to improve performance

wps-cloudformation-template.yaml
Ran up stack from scratch (sandbox) + discovered it couldn't write to status file.
=> Fix aggregation worker S3 access issue when writing status file.

wps-cloudformation-template.yaml
Some of this will later be stripped out, but removing params as an intermediate change
=> Evict some more template parameters

request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java, request-handler/src/main/java/au/org/aodn/aws/wps/operation/GetCapabilitiesReader.java
Log entire request body + parameters + ipaddress etc in a single un-broken line for consumption by SumoLogic.
**Request handler should now generate a log line similar to this for an Execute operation:**
1834 [main] INFO au.org.aodn.aws.wps.lambda.WpsLambdaRequestHandler - Operation [au.org.aodn.aws.wps.operation.ExecuteOperation] requested. IPAddress [131.217.38.93], Request body [<wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" …
=> Logging changes.  Log entire request body + parameters + ipaddress

wps-cloudformation-template.yaml
DON'T MERGE YET, UNTIL WE KNOW THE FILE DEPENDENCIES ARE HANDLED ELSEWHERE
=> Remove S3PutConfigurationFiles from template

wps-cloudformation-template.yaml
=> Tidy maps/conditions. Add comments to delineate resource sections.

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/HttpIndexReader.java, wps-common/src/main/java/au/org/aodn/aws/util/DescribeProcessHelper.java
=> Aggregation size reporting logging

dev.properties, wps-cloudformation-template.yaml
Makes the parameters the same as we decided we should have at the meeting.
Get rid of unwanted parameters. Remove default for geonetworkCatalogueURL. Move parameters without defaults to top. Fix dev.properties to point to developmnet docker image
=> Fix parameters.

wps-cloudformation-template.yaml
=> Lookup vpc using account/region instead of specifying it

aggregation-worker/pom.xml, aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/HttpIndexReader.java, aggregation-worker/src/main/resources/log4j2.xml, integration-testing/pom.xml, job-status-service/pom.xml, job-status-service/src/main/resources/log4j2.xml, request-handler/pom.xml, request-handler/src/main/resources/log4j2.xml, wps-cloudformation-template.yaml, wps-common/pom.xml, wps-common/src/main/java/au/org/aodn/aws/wps/status/WpsConfig.java
Change aggregator to use log4j2 sumologic appender to write logs directly to sumo HTTP endpoint.
Change lambda functions to use log4j2 lambda appender (for consistency of log framework).
Removed Batch log subscription.
=> Aggregator direct http sumo logging

aggregation-worker/pom.xml, job-status-service/pom.xml, request-handler/pom.xml, wps-common/pom.xml
Fixes https://github.com/aodn/issues/issues/159
=> Pin aws-java-sdk dependencies to avoid version mismatching

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/SubsetParameters.java, wps-common/src/main/resources/config/templates.xml
WIP: DO NOT MERGE AS PROTOTYPE
=> Handle z parameters/depth when running aggregations

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
Also proposed fix for ITs failing due to lat/long attributes being doubles (rather than strings). Hence the extra space after the last digit for lat/long attribute overrides
=> Add integration test for CARS depth subsetting

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
Should fix the broken ITs in combo with the PRs from yesterday
=> Fix depth range endpoint for integration testing CARS

job-status-service/src/main/java/au/org/aodn/aws/wps/lambda/JobStatusServiceRequestHandler.java, job-status-service/src/main/resources/templates/job_queue_html_template.ftl, wps-common/src/main/java/au/org/aodn/aws/util/AWSBatchUtil.java
Fix for this issue: https://github.com/aodn/backlog/issues/825
General tidy + performance improvements.
=> Handle number of Job IDs limit in DescribeJobs call

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
Also removed an unused method.
=> Add testmode transaction integration test

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/SubsetParameters.java
Required for https://github.com/aodn/geoserver-build/pull/274
=> verticalRange as a Number not Double

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/HttpIndexReader.java, aggregation-worker/src/main/java/au/org/emii/geoserver/client/TimeNotSupportedException.java, aggregation-worker/src/main/resources/templates/provenance_template_gridded.ftl
Fix bathy layer WPS check (and any other layers that don't have a time dimension)
=> Wps test transaction fix

job-status-service/src/main/resources/templates/job_status_html_template.ftl
https://github.com/aodn/backlog/issues/854
=> Update template to remove WPS status

wps-cloudformation-template.yaml
=> SecurityGroupIds must be a list of strings

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java, wps-common/src/main/java/au/org/aodn/aws/util/S3Utils.java
fixes https://github.com/aodn/issues/issues/363
=> Stream zip on the fly to s3

Dockerfile, Jenkinsfile, aggregation-worker/scripts/docker-build.sh, docker-compose.yml
Work in progress PR for declarative AWS WPS pipeline
=> Add Jenkinsfile and Dockerfile

aggregation-worker/src/main/java/au/org/emii/aggregationworker/AggregationRunner.java
Fixes the no-notification-email half of https://github.com/aodn/issues/issues/465
=> Treat amazon service client-caused errors the same as normal errors

wps-cloudformation-template.yaml, wps-common/src/main/java/au/org/aodn/aws/util/S3Utils.java
Fixes second half of https://github.com/aodn/issues/issues/465 (hopefully, given we couldn't actually test it on large aggregations)
=> Give aggregation process more memory

wps-common/src/main/java/au/org/aodn/aws/util/EmailService.java
fixes https://github.com/aodn/issues/issues/475
for reference https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
=> fixes issue #475

wps-cloudformation-template.yaml
Use same AMI for non-prod account as for prod as per test AMI.
Testing...
=> Fixes aodn/issues#474

request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java
Fixes https://github.com/aodn/issues/issues/486
=> Added appropriate HTTP statuses

wps-cloudformation-template.yaml
since this is an account global and we don't want different aws-wps stacks stepping on each others toes
part of fixing https://github.com/aodn/issues/issues/484
=> Don't create IAM role for log creation

request-handler/src/main/java/au/org/aodn/aws/wps/RequestParserFactory.java, request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java
Fixes https://github.com/aodn/issues/issues/506
=> Handle no parameters sent to request handler

request-handler/src/main/resources/templates/GetCapabilities.ftl
https://github.com/aodn/PO-Backlog/issues/33
=> Add service provider details to GetCapabilities statement

wps-common/src/main/resources/templates/jobComplete.vm, wps-common/src/main/resources/templates/jobFailed.vm, wps-common/src/main/resources/templates/jobRegistered.vm
=> Acknowledgement wording update

wps-cloudformation-template.yaml
Not attached to any backlog item, just noticed it. 
Assigning for review by @ccmoloney  since it's his comment in the template screaming at me "Please keep in sync with JobComputeEnvironment!!!!!"
=> Resync TestComputeEnvironment with JobComputeEnvironment

wps-cloudformation-template.yaml
For https://github.com/aodn/backlog/issues/3111
Draft for now. It's working and probably complete but I want to sleep on it to decide if there's any other changes I want to make
=> Make AWS-WPS work with new version of sumologic lambda collector

integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java
Update the sourceData parameter to GN3 style.
=> Fix ProvenanceRequested test

aggregation-worker/pom.xml, integration-testing/pom.xml, job-status-service/pom.xml, request-handler/pom.xml, wps-common/pom.xml
the branch for this built okay so please review @nspool
=> update log4j due to CVE-2021-44228

wps-cloudformation-template.yaml
restricts sending of email to specified value (e.g. *@aodn.org.au)
=> Add 'SesLimitRecipients' parameter

wps-cloudformation-template.yaml
Backlog: https://github.com/aodn/backlog/issues/3949
=> remove use of custom AMI

wps-cloudformation-template.yaml
~~DRAFT~~
Ready to merge
TODO:
- ~~still testing probably needs some additional mapping~~
- ~~need to add to test compute instance~~
=> add large EBS to EC2 using launch template

.github/workflows/build.yml, wps-cloudformation-template.yaml
use S3 endpoint instead of cloudfront
=> update default value for dataDownloadUrlPrefix
